[package]
name = "weather"
version = "0.1.0"
authors = ["Shamir Khodzha <khodzha.sh@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
serde_json = "1.0"
itertools = "0.7.3"

[dev-dependencies]
mockito = "0.9.0"
reqwest = "0.8.4"
